import { Controller, Get, Param, Post, Req, UploadedFile, UseGuards, UseInterceptors, BadRequestException } from '@nestjs/common';
import { FileInterceptor } from '@nestjs/platform-express';
import { AuthGuard } from '../auth/auth.guard';
import { PrescriptionService } from './prescription.service';
import { SyntheticPatientService } from '../dev/synthetic-patient.service';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Session } from '../database/entities/session.entity';
import { ForbiddenException, NotFoundException } from '@nestjs/common';
@Controller('dev/demo/patients/:patientId/prescriptions') @UseGuards(AuthGuard)
export class PrescriptionController { constructor(private readonly prescriptions: PrescriptionService, private readonly patients: SyntheticPatientService) {} private async ref(req: any, patientId: string) { const patient = await this.patients.get(req.user.tenantId, patientId); return `synthetic:${patient.syntheticPatientId}`; } @Post() @UseInterceptors(FileInterceptor('file')) async upload(@Param('patientId') patientId: string, @UploadedFile() file: any, @Req() req: any) { if (!file?.buffer) throw new BadRequestException('INVALID_FILE'); return this.prescriptions.upload(req.user.tenantId, await this.ref(req, patientId), { buffer: file.buffer, filename: file.originalname, mimeType: file.mimetype }); } @Get() async list(@Param('patientId') patientId: string, @Req() req: any) { return this.prescriptions.list(req.user.tenantId, await this.ref(req, patientId)); } @Post(':id/approve') approve(@Param('id') id: string, @Req() req: any) { return this.prescriptions.approve(req.user.tenantId, id); } }

@Controller('sessions/:sessionId/prescriptions') @UseGuards(AuthGuard)
export class PatientPrescriptionController { constructor(private readonly prescriptions: PrescriptionService, @InjectRepository(Session) private readonly sessions: Repository<Session>) {} private async ref(req: any, sessionId: string) { const session = await this.sessions.findOne({ where: { id: sessionId, tenantId: req.user.tenantId } }); if (!session) throw new NotFoundException('SESSION_NOT_FOUND'); if (!session.subjectAbhaRef.startsWith('synthetic:') && !session.subjectAbhaRef.startsWith('local-file:')) throw new ForbiddenException('PATIENT_PRESCRIPTION_UPLOAD_REQUIRES_DEVELOPMENT_SESSION'); return session.subjectAbhaRef; } @Post() @UseInterceptors(FileInterceptor('file')) async upload(@Param('sessionId') sessionId: string, @UploadedFile() file: any, @Req() req: any) { if (!file?.buffer) throw new BadRequestException('INVALID_FILE'); return this.prescriptions.upload(req.user.tenantId, await this.ref(req, sessionId), { buffer: file.buffer, filename: file.originalname, mimeType: file.mimetype }); } @Get() async list(@Param('sessionId') sessionId: string, @Req() req: any) { return this.prescriptions.list(req.user.tenantId, await this.ref(req, sessionId)); } }
